-- Mock Comments Data
-- Creating 400 realistic comments on posts from various users

INSERT INTO comments (post_id, user_id, content, created_at, updated_at) VALUES
-- Comments on John's posts (posts 1-12)
(1, 2, 'React 18 is a game changer! The concurrent features are exactly what we needed.', datetime('now', '-350 days', '+2 hours'), datetime('now', '-350 days', '+2 hours')),
(1, 3, 'Great post John! Have you tried the new Suspense features yet?', datetime('now', '-350 days', '+3 hours'), datetime('now', '-350 days', '+3 hours')),
(1, 5, 'This convinced me to upgrade our production app. Thanks for the detailed breakdown!', datetime('now', '-349 days'), datetime('now', '-349 days')),
(1, 6, 'The performance improvements are incredible. Our app loads 30% faster now.', datetime('now', '-349 days', '+2 hours'), datetime('now', '-349 days', '+2 hours')),
(1, 7, 'Excellent insights! The concurrent rendering explanation was spot on.', datetime('now', '-348 days'), datetime('now', '-348 days')),
(2, 2, 'Beautiful shot! Nature always finds a way to inspire us.', datetime('now', '-340 days', '+1 hour'), datetime('now', '-340 days', '+1 hour')),
(2, 6, 'This is stunning! The colors are perfect. Nature is the best artist 🎨', datetime('now', '-339 days'), datetime('now', '-339 days')),
(2, 10, 'Such peaceful vibes. Makes me want to go for a walk right now!', datetime('now', '-339 days', '+2 hours'), datetime('now', '-339 days', '+2 hours')),
(3, 7, 'Go is such a powerful language. The concurrency model is brilliant!', datetime('now', '-330 days', '+1 hour'), datetime('now', '-330 days', '+1 hour')),
(3, 5, 'I''ve been learning Go too. Any recommendations for good resources?', datetime('now', '-329 days'), datetime('now', '-329 days')),
(3, 13, 'The simplicity of Go is what drew me in. No more complex inheritance hierarchies!', datetime('now', '-329 days', '+3 hours'), datetime('now', '-329 days', '+3 hours')),
(4, 2, 'Congrats on the new startup! AI development tools are the future.', datetime('now', '-320 days', '+1 hour'), datetime('now', '-320 days', '+1 hour')),
(4, 5, 'This is exactly what the industry needs. Excited to see what you build!', datetime('now', '-319 days'), datetime('now', '-319 days')),
(4, 16, 'AI-powered development? Count me in! What''s your tech stack?', datetime('now', '-319 days', '+2 hours'), datetime('now', '-319 days', '+2 hours')),
(5, 3, 'REST APIs in Go are so clean. Love the standard library approach.', datetime('now', '-310 days', '+1 hour'), datetime('now', '-310 days', '+1 hour')),
(5, 7, 'Great work! The error handling in Go makes APIs so much more robust.', datetime('now', '-309 days'), datetime('now', '-309 days')),
(5, 24, 'This inspired me to rewrite our microservices in Go. Thanks for sharing!', datetime('now', '-309 days', '+3 hours'), datetime('now', '-309 days', '+3 hours')),
(6, 2, 'Debugging tip: I use a lot of logging too. Sometimes it''s the simplest solutions!', datetime('now', '-300 days', '+1 hour'), datetime('now', '-300 days', '+1 hour')),
(6, 9, 'Console.log is my best friend during development 😂', datetime('now', '-299 days'), datetime('now', '-299 days')),
(6, 15, 'I prefer debugger breakpoints, but logging has its place too!', datetime('now', '-299 days', '+2 hours'), datetime('now', '-299 days', '+2 hours')),
(7, 2, 'Amazing achievement! What''s your training routine like?', datetime('now', '-290 days', '+1 hour'), datetime('now', '-290 days', '+1 hour')),
(7, 9, 'Inspiring! I need to get back into running. Any beginner tips?', datetime('now', '-289 days'), datetime('now', '-289 days')),
(7, 11, 'Consistency is key. You''re proving that hard work pays off!', datetime('now', '-289 days', '+3 hours'), datetime('now', '-289 days', '+3 hours')),
(8, 5, 'Authentication can be tricky. JWT is solid choice for most apps.', datetime('now', '-280 days', '+1 hour'), datetime('now', '-280 days', '+1 hour')),
(8, 7, 'Security first! Great to see you prioritizing this early on.', datetime('now', '-279 days'), datetime('now', '-279 days')),
(8, 13, 'Have you considered OAuth2 flows? They''re more complex but more secure.', datetime('now', '-279 days', '+2 hours'), datetime('now', '-279 days', '+2 hours')),
(9, 2, 'Coffee and code - the perfect combination ☕👨‍💻 What''s your coding fuel?', datetime('now', '-270 days', '+1 hour'), datetime('now', '-270 days', '+1 hour')),
(9, 10, 'I''m a tea person myself, but coffee gets the job done too!', datetime('now', '-269 days'), datetime('now', '-269 days')),
(9, 14, 'Energy drinks for those late-night coding sessions! ⚡', datetime('now', '-269 days', '+3 hours'), datetime('now', '-269 days', '+3 hours')),
(10, 2, 'Congrats on the deployment! That first production push is always nerve-wracking.', datetime('now', '-260 days', '+1 hour'), datetime('now', '-260 days', '+1 hour')),
(10, 5, 'Celebrating the small wins! Deployment success is a big deal.', datetime('now', '-259 days'), datetime('now', '-259 days')),
(10, 16, 'What monitoring tools are you using for production? Always good to know.', datetime('now', '-259 days', '+2 hours'), datetime('now', '-259 days', '+2 hours')),
(11, 5, 'Microservices are complex but so rewarding. Great choice!', datetime('now', '-250 days', '+1 hour'), datetime('now', '-250 days', '+1 hour')),
(11, 7, 'The scalability benefits are worth the complexity. Well done!', datetime('now', '-249 days'), datetime('now', '-249 days')),
(11, 24, 'Have you considered service mesh for inter-service communication?', datetime('now', '-249 days', '+3 hours'), datetime('now', '-249 days', '+3 hours')),
(12, 2, 'Senior Developer! That''s awesome. Hard work really does pay off 💪', datetime('now', '-240 days', '+1 hour'), datetime('now', '-240 days', '+1 hour')),
(12, 5, 'Congrats! What''s the biggest lesson you learned on this journey?', datetime('now', '-239 days'), datetime('now', '-239 days')),
(12, 16, 'Inspiring career progression. Keep crushing those goals!', datetime('now', '-239 days', '+2 hours'), datetime('now', '-239 days', '+2 hours')),

-- Comments on Sarah's posts (posts 13-24)
(13, 1, 'Digital nomad life sounds amazing! How do you stay productive while traveling?', datetime('now', '-315 days', '+1 hour'), datetime('now', '-315 days', '+1 hour')),
(13, 6, 'Barcelona is magical! The architecture is truly inspiring.', datetime('now', '-314 days'), datetime('now', '-314 days')),
(13, 9, 'I''ve been to Barcelona too. Sagrada Familia is mind-blowing!', datetime('now', '-314 days', '+2 hours'), datetime('now', '-314 days', '+2 hours')),
(14, 1, 'Content creation tip: Storytelling is everything. People connect with stories!', datetime('now', '-305 days', '+1 hour'), datetime('now', '-305 days', '+1 hour')),
(14, 7, 'Love this approach. Authenticity builds real connections online.', datetime('now', '-304 days'), datetime('now', '-304 days')),
(14, 10, 'Storytelling has transformed my content strategy too. Great advice!', datetime('now', '-304 days', '+3 hours'), datetime('now', '-304 days', '+3 hours')),
(15, 3, 'Morning yoga is the best way to start the day 🧘‍♀️', datetime('now', '-295 days', '+1 hour'), datetime('now', '-295 days', '+1 hour')),
(15, 8, 'Such peaceful energy! Yoga has changed my life too.', datetime('now', '-294 days'), datetime('now', '-294 days')),
(15, 17, 'What style of yoga do you practice? I''m looking for recommendations.', datetime('now', '-294 days', '+2 hours'), datetime('now', '-294 days', '+2 hours')),
(16, 1, 'Amazing results! What was your campaign strategy?', datetime('now', '-285 days', '+1 hour'), datetime('now', '-285 days', '+1 hour')),
(16, 5, '150% engagement increase is phenomenal! What platform worked best?', datetime('now', '-284 days'), datetime('now', '-284 days')),
(16, 9, 'This is inspiring. Any chance you''d share more campaign details?', datetime('now', '-284 days', '+3 hours'), datetime('now', '-284 days', '+3 hours')),
(17, 3, 'Healthy eating made easy! Meal prep is a game changer.', datetime('now', '-275 days', '+1 hour'), datetime('now', '-275 days', '+1 hour')),
(17, 11, 'Love the meal prep approach. What''s your favorite healthy recipe?', datetime('now', '-274 days'), datetime('now', '-274 days')),
(17, 18, 'Meal prep Sundays are the best. Sets you up for success all week!', datetime('now', '-274 days', '+2 hours'), datetime('now', '-274 days', '+2 hours')),
(18, 2, 'Networking events are so valuable. Met amazing people tonight too!', datetime('now', '-265 days', '+1 hour'), datetime('now', '-265 days', '+1 hour')),
(18, 7, 'The energy at these events is contagious. Love meeting fellow entrepreneurs!', datetime('now', '-264 days'), datetime('now', '-264 days')),
(18, 16, 'Networking is underrated. So many opportunities come from connections.', datetime('now', '-264 days', '+3 hours'), datetime('now', '-264 days', '+3 hours')),
(19, 6, 'Reading is so important. What''s your current read?', datetime('now', '-255 days', '+1 hour'), datetime('now', '-255 days', '+1 hour')),
(19, 8, 'Atomic Habits changed my life too. Such practical advice!', datetime('now', '-254 days'), datetime('now', '-254 days')),
(19, 21, 'Love that you''re reading. Books are the best teachers.', datetime('now', '-254 days', '+2 hours'), datetime('now', '-254 days', '+2 hours')),
(20, 3, 'Nature therapy is real! Hiking clears the mind like nothing else.', datetime('now', '-245 days', '+1 hour'), datetime('now', '-245 days', '+1 hour')),
(20, 9, 'Disconnecting to reconnect - so important in our digital world.', datetime('now', '-244 days'), datetime('now', '-244 days')),
(20, 17, 'The mountains are calling! Time for my next hiking trip.', datetime('now', '-244 days', '+3 hours'), datetime('now', '-244 days', '+3 hours')),

-- Comments on Mike's posts (posts 25-34)
(25, 1, 'Amazing PR! What''s your weekly mileage?', datetime('now', '-340 days', '+1 hour'), datetime('now', '-340 days', '+1 hour')),
(25, 2, 'Inspiring! I need to get back into running too.', datetime('now', '-339 days'), datetime('now', '-339 days')),
(25, 9, 'Consistency pays off. You''re motivating me to lace up!', datetime('now', '-339 days', '+2 hours'), datetime('now', '-339 days', '+2 hours')),
(26, 2, 'Playoff basketball is the best! Such intense games.', datetime('now', '-330 days', '+1 hour'), datetime('now', '-330 days', '+1 hour')),
(26, 7, 'That final shot must have been epic! Love the drama of playoffs.', datetime('now', '-329 days'), datetime('now', '-329 days')),
(26, 15, 'Basketball season is my favorite time of year!', datetime('now', '-329 days', '+3 hours'), datetime('now', '-329 days', '+3 hours')),
(27, 6, 'Functional fitness is so important. How has it changed your daily life?', datetime('now', '-320 days', '+1 hour'), datetime('now', '-320 days', '+1 hour')),
(27, 10, 'Love this approach. Everyday activities feel easier now.', datetime('now', '-319 days'), datetime('now', '-319 days')),
(27, 20, 'Functional fitness transformed how I move. Great post!', datetime('now', '-319 days', '+2 hours'), datetime('now', '-319 days', '+2 hours')),
(28, 2, 'Meal prep Sundays are the best! What''s your go-to protein?', datetime('now', '-310 days', '+1 hour'), datetime('now', '-310 days', '+1 hour')),
(28, 6, 'Healthy eating made easy. Love your approach!', datetime('now', '-309 days'), datetime('now', '-309 days')),
(28, 18, 'Meal prep has changed my life. Thanks for the inspiration!', datetime('now', '-309 days', '+3 hours'), datetime('now', '-309 days', '+3 hours')),
(29, 5, 'CrossFit is intense! How long have you been doing it?', datetime('now', '-300 days', '+1 hour'), datetime('now', '-300 days', '+1 hour')),
(29, 9, 'The community aspect of CrossFit is amazing!', datetime('now', '-299 days'), datetime('now', '-299 days')),
(29, 15, 'CrossFit competitions are next level. Respect!', datetime('now', '-299 days', '+2 hours'), datetime('now', '-299 days', '+2 hours')),
(30, 7, 'Recovery is underrated. Great reminder!', datetime('now', '-290 days', '+1 hour'), datetime('now', '-290 days', '+1 hour')),
(30, 11, 'Rest days are just as important as training days.', datetime('now', '-289 days'), datetime('now', '-289 days')),
(30, 20, 'Balance is key. Love this perspective!', datetime('now', '-289 days', '+3 hours'), datetime('now', '-289 days', '+3 hours')),
(31, 2, 'Whole foods are the way to go! What''s your favorite superfood?', datetime('now', '-280 days', '+1 hour'), datetime('now', '-280 days', '+1 hour')),
(31, 6, 'Nutrition advice that actually makes sense. Thanks!', datetime('now', '-279 days'), datetime('now', '-279 days')),
(31, 17, 'Blueberries are my go-to superfood. What about you?', datetime('now', '-279 days', '+2 hours'), datetime('now', '-279 days', '+2 hours')),
(32, 5, 'Marathon training is no joke. You''ve got this!', datetime('now', '-270 days', '+1 hour'), datetime('now', '-270 days', '+1 hour')),
(32, 9, 'Mental toughness is everything in long-distance running.', datetime('now', '-269 days'), datetime('now', '-269 days')),
(32, 28, 'The marathon journey is as much mental as physical.', datetime('now', '-269 days', '+3 hours'), datetime('now', '-269 days', '+3 hours')),
(33, 2, 'Group fitness energy is contagious! Love it.', datetime('now', '-260 days', '+1 hour'), datetime('now', '-260 days', '+1 hour')),
(33, 10, 'Community makes fitness so much more enjoyable.', datetime('now', '-259 days'), datetime('now', '-259 days')),
(33, 18, 'The best workouts happen with great people!', datetime('now', '-259 days', '+2 hours'), datetime('now', '-259 days', '+2 hours')),
(34, 7, 'Rest is productive too. Great mindset!', datetime('now', '-250 days', '+1 hour'), datetime('now', '-250 days', '+1 hour')),
(34, 11, 'Sometimes the best workout is the one you skip.', datetime('now', '-249 days'), datetime('now', '-249 days')),
(34, 20, 'Recovery is where the magic happens. Well said!', datetime('now', '-249 days', '+3 hours'), datetime('now', '-249 days', '+3 hours')),

-- Comments on Alice's posts (posts 35-40)
(35, 2, 'Your art is stunning! What inspires your landscapes?', datetime('now', '-335 days', '+1 hour'), datetime('now', '-335 days', '+1 hour')),
(35, 6, 'Nature through your eyes is absolutely beautiful.', datetime('now', '-334 days'), datetime('now', '-334 days')),
(35, 14, 'Such peaceful and inspiring artwork. Love it!', datetime('now', '-334 days', '+2 hours'), datetime('now', '-334 days', '+2 hours')),
(36, 2, 'The cinematography in this movie sounds amazing!', datetime('now', '-325 days', '+1 hour'), datetime('now', '-325 days', '+1 hour')),
(36, 10, 'I loved that movie too! The visuals were stunning.', datetime('now', '-324 days'), datetime('now', '-324 days')),
(36, 25, 'Great review. Makes me want to watch it again.', datetime('now', '-324 days', '+3 hours'), datetime('now', '-324 days', '+3 hours')),
(37, 6, 'Teaching art must be so rewarding! Such a noble profession.', datetime('now', '-315 days', '+1 hour'), datetime('now', '-315 days', '+1 hour')),
(37, 8, 'Inspiring the next generation of artists. Beautiful!', datetime('now', '-314 days'), datetime('now', '-314 days')),
(37, 21, 'Art education is so important. Thanks for doing this work!', datetime('now', '-314 days', '+2 hours'), datetime('now', '-314 days', '+2 hours')),
(38, 6, 'Love the branding work! What''s your design process?', datetime('now', '-305 days', '+1 hour'), datetime('now', '-305 days', '+1 hour')),
(38, 14, 'Such clean and effective design. Well done!', datetime('now', '-304 days'), datetime('now', '-304 days')),
(38, 25, 'The logo really captures the brand essence perfectly.', datetime('now', '-304 days', '+3 hours'), datetime('now', '-304 days', '+3 hours')),
(39, 2, 'Abstract art is so fascinating. What does this piece mean to you?', datetime('now', '-295 days', '+1 hour'), datetime('now', '-295 days', '+1 hour')),
(39, 10, 'Love exploring abstract styles. So much freedom in it!', datetime('now', '-294 days'), datetime('now', '-294 days')),
(39, 14, 'Abstract art speaks to the soul. Beautiful work!', datetime('now', '-294 days', '+2 hours'), datetime('now', '-294 days', '+2 hours')),
(40, 6, 'Client work that you''re proud of is the best feeling!', datetime('now', '-285 days', '+1 hour'), datetime('now', '-285 days', '+1 hour')),
(40, 14, 'Such professional and creative work. Inspiring!', datetime('now', '-284 days'), datetime('now', '-284 days')),
(40, 25, 'The design really elevates the brand. Great job!', datetime('now', '-284 days', '+3 hours'), datetime('now', '-284 days', '+3 hours')),

-- Comments on David's posts (posts 41-48)
(41, 1, 'AI is evolving so fast! What developments are you most excited about?', datetime('now', '-325 days', '+1 hour'), datetime('now', '-325 days', '+1 hour')),
(41, 7, 'GPT-4 capabilities are mind-blowing. The future is here!', datetime('now', '-324 days'), datetime('now', '-324 days')),
(41, 13, 'AI is transforming everything. Exciting times!', datetime('now', '-324 days', '+2 hours'), datetime('now', '-324 days', '+2 hours')),
(42, 1, 'Climate tech is where it''s at. Technology can solve these problems!', datetime('now', '-315 days', '+1 hour'), datetime('now', '-315 days', '+1 hour')),
(42, 17, 'Promising developments in climate solutions. Hopeful!', datetime('now', '-314 days'), datetime('now', '-314 days')),
(42, 27, 'Technology and policy together can make a difference.', datetime('now', '-314 days', '+3 hours'), datetime('now', '-314 days', '+3 hours')),
(43, 1, 'Blockchain beyond crypto is fascinating. Supply chain transparency is huge!', datetime('now', '-305 days', '+1 hour'), datetime('now', '-305 days', '+1 hour')),
(43, 7, 'The potential applications are endless. Great insights!', datetime('now', '-304 days'), datetime('now', '-304 days')),
(43, 16, 'Blockchain is revolutionizing trust and transparency.', datetime('now', '-304 days', '+2 hours'), datetime('now', '-304 days', '+2 hours')),
(44, 3, 'Product roadmaps need to balance vision with user needs.', datetime('now', '-295 days', '+1 hour'), datetime('now', '-295 days', '+1 hour')),
(44, 7, 'User-centric prioritization is key. Love this approach!', datetime('now', '-294 days'), datetime('now', '-294 days')),
(44, 16, 'Roadmap planning that puts users first. Perfect!', datetime('now', '-294 days', '+3 hours'), datetime('now', '-294 days', '+3 hours')),
(45, 1, 'Exciting product launch! What metrics are you tracking?', datetime('now', '-285 days', '+1 hour'), datetime('now', '-285 days', '+1 hour')),
(45, 5, '40% improvement is huge! Congrats on the success.', datetime('now', '-284 days'), datetime('now', '-284 days')),
(45, 16, 'User testing pays off. Great results!', datetime('now', '-284 days', '+2 hours'), datetime('now', '-284 days', '+2 hours')),
(46, 3, 'Startup life in a nutshell! Coffee, code, and customer feedback.', datetime('now', '-275 days', '+1 hour'), datetime('now', '-275 days', '+1 hour')),
(46, 7, 'The startup grind is real. You''ve got this!', datetime('now', '-274 days'), datetime('now', '-274 days')),
(46, 16, 'Building products that matter. Inspiring journey!', datetime('now', '-274 days', '+3 hours'), datetime('now', '-274 days', '+3 hours')),
(47, 5, 'Product conferences are goldmines of insights!', datetime('now', '-265 days', '+1 hour'), datetime('now', '-265 days', '+1 hour')),
(47, 13, 'So many innovative ideas floating around. Love it!', datetime('now', '-264 days'), datetime('now', '-264 days')),
(47, 24, 'Product conferences fuel innovation. Great experience!', datetime('now', '-264 days', '+2 hours'), datetime('now', '-264 days', '+2 hours')),
(48, 1, 'Data-driven decisions are the future of product development.', datetime('now', '-255 days', '+1 hour'), datetime('now', '-255 days', '+1 hour')),
(48, 7, 'A/B testing is powerful. Love seeing this in action!', datetime('now', '-254 days'), datetime('now', '-254 days')),
(48, 16, 'User experience backed by data. Perfect combination!', datetime('now', '-254 days', '+3 hours'), datetime('now', '-254 days', '+3 hours')),

-- Comments on Emma's posts (posts 49-56)
(49, 1, 'Homemade pasta is the best! What''s your sauce recipe?', datetime('now', '-320 days', '+1 hour'), datetime('now', '-320 days', '+1 hour')),
(49, 2, 'Fresh pasta night sounds amazing. Love the tradition!', datetime('now', '-319 days'), datetime('now', '-319 days')),
(49, 18, 'Homemade pasta is worth the effort. So delicious!', datetime('now', '-319 days', '+2 hours'), datetime('now', '-319 days', '+2 hours')),
(50, 2, 'Hiking is such great therapy. Nature heals everything.', datetime('now', '-310 days', '+1 hour'), datetime('now', '-310 days', '+1 hour')),
(50, 9, '15 miles is impressive! What trail was it?', datetime('now', '-309 days'), datetime('now', '-309 days')),
(50, 17, 'Disconnecting and reconnecting with nature is essential.', datetime('now', '-309 days', '+3 hours'), datetime('now', '-309 days', '+3 hours')),
(51, 2, 'Florence food markets are incredible. Such vibrant culture!', datetime('now', '-300 days', '+1 hour'), datetime('now', '-300 days', '+1 hour')),
(51, 10, 'Italian markets are a food lover''s paradise!', datetime('now', '-299 days'), datetime('now', '-299 days')),
(51, 18, 'Fresh produce like that makes cooking a joy.', datetime('now', '-299 days', '+2 hours'), datetime('now', '-299 days', '+2 hours')),
(52, 1, 'UX principle: Keep it simple. So important and often forgotten!', datetime('now', '-290 days', '+1 hour'), datetime('now', '-290 days', '+1 hour')),
(52, 7, 'User-centered design is everything. Love this focus!', datetime('now', '-289 days'), datetime('now', '-289 days')),
(52, 25, 'Simplicity in design leads to better user experience.', datetime('now', '-289 days', '+3 hours'), datetime('now', '-289 days', '+3 hours')),
(53, 1, '98% WCAG compliance is outstanding! Accessibility matters.', datetime('now', '-280 days', '+1 hour'), datetime('now', '-280 days', '+1 hour')),
(53, 2, 'Making the web inclusive for everyone. Thank you!', datetime('now', '-279 days'), datetime('now', '-279 days')),
(53, 7, 'Accessibility should be everyone''s priority. Great work!', datetime('now', '-279 days', '+2 hours'), datetime('now', '-279 days', '+2 hours')),
(54, 5, 'Design systems are game changers for consistency.', datetime('now', '-270 days', '+1 hour'), datetime('now', '-270 days', '+1 hour')),
(54, 7, 'Scalable design through systems. Love this approach!', datetime('now', '-269 days'), datetime('now', '-269 days')),
(54, 25, 'Design systems make collaboration so much easier.', datetime('now', '-269 days', '+3 hours'), datetime('now', '-269 days', '+3 hours')),
(55, 1, 'User research is the foundation of good design.', datetime('now', '-260 days', '+1 hour'), datetime('now', '-260 days', '+1 hour')),
(55, 6, 'Understanding users leads to better products. Truth!', datetime('now', '-259 days'), datetime('now', '-259 days')),
(55, 14, 'User research transforms design decisions.', datetime('now', '-259 days', '+2 hours'), datetime('now', '-259 days', '+2 hours')),
(56, 2, 'Design challenges are the best way to learn and grow!', datetime('now', '-250 days', '+1 hour'), datetime('now', '-250 days', '+1 hour')),
(56, 10, 'Pushing creative boundaries. Love this challenge!', datetime('now', '-249 days'), datetime('now', '-249 days')),
(56, 25, 'Banking app redesign challenge sounds fascinating!', datetime('now', '-249 days', '+3 hours'), datetime('now', '-249 days', '+3 hours')),

-- Comments on James's posts (posts 57-66)
(57, 2, 'Champions League finals are always epic! What a match!', datetime('now', '-315 days', '+1 hour'), datetime('now', '-315 days', '+1 hour')),
(57, 3, 'Football at its finest. The drama, the skill, the passion!', datetime('now', '-314 days'), datetime('now', '-314 days')),
(57, 9, 'CL finals bring out the best in teams. Amazing!', datetime('now', '-314 days', '+2 hours'), datetime('now', '-314 days', '+2 hours')),
(58, 2, 'RPGs are my favorite genre. What made this one special?', datetime('now', '-305 days', '+1 hour'), datetime('now', '-305 days', '+1 hour')),
(58, 9, 'Gaming with friends is the best. Love the community aspect!', datetime('now', '-304 days'), datetime('now', '-304 days')),
(58, 15, 'Character development in RPGs is everything. Well said!', datetime('now', '-304 days', '+3 hours'), datetime('now', '-304 days', '+3 hours')),
(59, 2, 'Family time is precious. Balance is so important!', datetime('now', '-295 days', '+1 hour'), datetime('now', '-295 days', '+1 hour')),
(59, 10, 'Simple moments create the best memories. Beautiful!', datetime('now', '-294 days'), datetime('now', '-294 days')),
(59, 21, 'Family BBQ sounds perfect. Cherish these moments!', datetime('now', '-294 days', '+2 hours'), datetime('now', '-294 days', '+2 hours')),
(60, 1, 'Open source contributions make the world better. Proud of you!', datetime('now', '-285 days', '+1 hour'), datetime('now', '-285 days', '+1 hour')),
(60, 5, 'Community collaboration at its finest. Love this!', datetime('now', '-284 days'), datetime('now', '-284 days')),
(60, 13, 'Open source is the future of software development.', datetime('now', '-284 days', '+3 hours'), datetime('now', '-284 days', '+3 hours')),
(61, 1, 'Rust is powerful but challenging. Worth the learning curve!', datetime('now', '-275 days', '+1 hour'), datetime('now', '-275 days', '+1 hour')),
(61, 5, 'Memory safety without garbage collection is brilliant!', datetime('now', '-274 days'), datetime('now', '-274 days')),
(61, 24, 'Rust is changing systems programming. Exciting times!', datetime('now', '-274 days', '+2 hours'), datetime('now', '-274 days', '+2 hours')),
(62, 1, 'Code reviews should focus on logic and maintainability. Agree!', datetime('now', '-265 days', '+1 hour'), datetime('now', '-265 days', '+1 hour')),
(62, 5, 'Good code review culture makes teams stronger.', datetime('now', '-264 days'), datetime('now', '-264 days')),
(62, 7, 'Focus on improvement, not criticism. Perfect mindset!', datetime('now', '-264 days', '+3 hours'), datetime('now', '-264 days', '+3 hours')),
(63, 1, 'Hackathons are intense but so rewarding! What did you build?', datetime('now', '-255 days', '+1 hour'), datetime('now', '-255 days', '+1 hour')),
(63, 5, '48 hours of pure coding adrenaline. Love it!', datetime('now', '-254 days'), datetime('now', '-254 days')),
(63, 16, 'Hackathons spark innovation. Great experience!', datetime('now', '-254 days', '+2 hours'), datetime('now', '-254 days', '+2 hours')),
(64, 2, 'Tech meetups are incredible learning opportunities!', datetime('now', '-245 days', '+1 hour'), datetime('now', '-245 days', '+1 hour')),
(64, 10, 'Networking and knowledge sharing. Perfect combo!', datetime('now', '-244 days'), datetime('now', '-244 days')),
(64, 20, 'Tech communities are so vibrant. Love being part of it!', datetime('now', '-244 days', '+3 hours'), datetime('now', '-244 days', '+3 hours')),
(65, 1, 'CI/CD pipelines are essential for modern development.', datetime('now', '-235 days', '+1 hour'), datetime('now', '-235 days', '+1 hour')),
(65, 5, 'Automated deployments change everything. Well done!', datetime('now', '-234 days'), datetime('now', '-234 days')),
(65, 24, 'DevOps practices make development so much smoother.', datetime('now', '-234 days', '+2 hours'), datetime('now', '-234 days', '+2 hours')),
(66, 2, 'Weather APIs are surprisingly useful. Great project!', datetime('now', '-225 days', '+1 hour'), datetime('now', '-225 days', '+1 hour')),
(66, 10, 'Real-time data integration is powerful. Nice work!', datetime('now', '-224 days'), datetime('now', '-224 days')),
(66, 25, 'APIs open up so many possibilities. Well executed!', datetime('now', '-224 days', '+3 hours'), datetime('now', '-224 days', '+3 hours')),

-- Comments on Lisa's posts (posts 67-72)
(67, 6, 'Machine learning accuracy improvements are so satisfying!', datetime('now', '-310 days', '+1 hour'), datetime('now', '-310 days', '+1 hour')),
(67, 13, 'Data quality is indeed the foundation. Well said!', datetime('now', '-309 days'), datetime('now', '-309 days')),
(67, 17, 'ML model tuning is an art and a science. Great insights!', datetime('now', '-309 days', '+2 hours'), datetime('now', '-309 days', '+2 hours')),
(68, 6, 'Deep learning conferences are mind-expanding experiences!', datetime('now', '-300 days', '+1 hour'), datetime('now', '-300 days', '+1 hour')),
(68, 13, 'Neural networks are fascinating. Love the complexity!', datetime('now', '-299 days'), datetime('now', '-299 days')),
(68, 30, 'AI research is moving so fast. Exciting to be part of it!', datetime('now', '-299 days', '+3 hours'), datetime('now', '-299 days', '+3 hours')),
(69, 6, 'Data visualization choices can make or break insights.', datetime('now', '-290 days', '+1 hour'), datetime('now', '-290 days', '+1 hour')),
(69, 17, 'Choose the right chart for your story. Perfect advice!', datetime('now', '-289 days'), datetime('now', '-289 days')),
(69, 21, 'Data storytelling through visualization. So important!', datetime('now', '-289 days', '+2 hours'), datetime('now', '-289 days', '+2 hours')),
(70, 6, 'Recommendation systems are everywhere now. Fascinating field!', datetime('now', '-280 days', '+1 hour'), datetime('now', '-280 days', '+1 hour')),
(70, 13, 'Collaborative filtering algorithms are so clever!', datetime('now', '-279 days'), datetime('now', '-279 days')),
(70, 30, 'Personalization through ML. The future of user experience!', datetime('now', '-279 days', '+3 hours'), datetime('now', '-279 days', '+3 hours')),
(71, 6, 'Big data processing challenges are real but solvable!', datetime('now', '-270 days', '+1 hour'), datetime('now', '-270 days', '+1 hour')),
(71, 13, 'Distributed computing is powerful. Great work!', datetime('now', '-269 days'), datetime('now', '-269 days')),
(71, 24, 'Scaling data processing is a complex but rewarding challenge.', datetime('now', '-269 days', '+2 hours'), datetime('now', '-269 days', '+2 hours')),
(72, 6, 'Research paper acceptance is a big deal! Congrats!', datetime('now', '-260 days', '+1 hour'), datetime('now', '-260 days', '+1 hour')),
(72, 13, 'Computer vision applications are exploding. Exciting field!', datetime('now', '-259 days'), datetime('now', '-259 days')),
(72, 17, 'Sharing research with the community. Love this!', datetime('now', '-259 days', '+3 hours'), datetime('now', '-259 days', '+3 hours')),

-- Comments on Ryan's posts (posts 73-78)
(73, 3, 'Live music is magical! What was the venue like?', datetime('now', '-305 days', '+1 hour'), datetime('now', '-305 days', '+1 hour')),
(73, 7, 'Concert experiences are unforgettable. Great review!', datetime('now', '-304 days'), datetime('now', '-304 days')),
(73, 15, 'Live performances have a special energy. Love it!', datetime('now', '-304 days', '+2 hours'), datetime('now', '-304 days', '+2 hours')),
(74, 2, 'Farmers markets support local communities. Love this!', datetime('now', '-295 days', '+1 hour'), datetime('now', '-295 days', '+1 hour')),
(74, 6, 'Organic and local is the way to go. So much better!', datetime('now', '-294 days'), datetime('now', '-294 days')),
(74, 18, 'Fresh bread from local bakers is unbeatable!', datetime('now', '-294 days', '+3 hours'), datetime('now', '-294 days', '+3 hours')),
(75, 2, 'Road trips are the best adventures! Where did you go?', datetime('now', '-285 days', '+1 hour'), datetime('now', '-285 days', '+1 hour')),
(75, 10, 'Freedom of the open road. Nothing beats it!', datetime('now', '-284 days'), datetime('now', '-284 days')),
(75, 20, 'Spontaneous discoveries make road trips magical.', datetime('now', '-284 days', '+2 hours'), datetime('now', '-284 days', '+2 hours')),
(76, 3, 'Golden hour photography is magical. Such beautiful light!', datetime('now', '-275 days', '+1 hour'), datetime('now', '-275 days', '+1 hour')),
(76, 9, 'Lighting makes all the difference in photography.', datetime('now', '-274 days'), datetime('now', '-274 days')),
(76, 25, 'Golden hour shots are always stunning. Well captured!', datetime('now', '-274 days', '+3 hours'), datetime('now', '-274 days', '+3 hours')),
(77, 3, 'Wedding photography captures love stories. Beautiful work!', datetime('now', '-265 days', '+1 hour'), datetime('now', '-265 days', '+1 hour')),
(77, 10, 'Emotional moments frozen in time. Love this!', datetime('now', '-264 days'), datetime('now', '-264 days')),
(77, 14, 'Wedding days are so special. Great captures!', datetime('now', '-264 days', '+2 hours'), datetime('now', '-264 days', '+2 hours')),
(78, 3, 'Drone photography opens new perspectives. Amazing!', datetime('now', '-255 days', '+1 hour'), datetime('now', '-255 days', '+1 hour')),
(78, 9, 'Aerial views change everything. So much potential!', datetime('now', '-254 days'), datetime('now', '-254 days')),
(78, 25, 'The world looks different from above. Incredible!', datetime('now', '-254 days', '+3 hours'), datetime('now', '-254 days', '+3 hours')),

-- Comments on Sophia's posts (posts 79-86)
(79, 2, 'Social media engagement growth is so rewarding!', datetime('now', '-300 days', '+1 hour'), datetime('now', '-300 days', '+1 hour')),
(79, 6, '200% increase is phenomenal! What changed?', datetime('now', '-299 days'), datetime('now', '-299 days')),
(79, 10, 'Engagement metrics that matter. Great results!', datetime('now', '-299 days', '+2 hours'), datetime('now', '-299 days', '+2 hours')),
(80, 2, 'Content creation is about genuine connection. Love this!', datetime('now', '-290 days', '+1 hour'), datetime('now', '-290 days', '+1 hour')),
(80, 6, 'Authenticity builds trust. So important online!', datetime('now', '-289 days'), datetime('now', '-289 days')),
(80, 14, 'Stories that resonate create loyal audiences.', datetime('now', '-289 days', '+3 hours'), datetime('now', '-289 days', '+3 hours')),
(81, 2, 'Algorithm changes keep us on our toes! Adapt or die.', datetime('now', '-280 days', '+1 hour'), datetime('now', '-280 days', '+1 hour')),
(81, 6, 'Instagram algorithm is a moving target. Stay agile!', datetime('now', '-279 days'), datetime('now', '-279 days')),
(81, 10, 'Content strategy evolution is constant. Love it!', datetime('now', '-279 days', '+2 hours'), datetime('now', '-279 days', '+2 hours')),
(82, 2, 'Brand collaborations done right. What made this one special?', datetime('now', '-270 days', '+1 hour'), datetime('now', '-270 days', '+1 hour')),
(82, 6, 'Cross-promotion that feels authentic. Perfect!', datetime('now', '-269 days'), datetime('now', '-269 days')),
(82, 14, 'Brand partnerships that align with values work best.', datetime('now', '-269 days', '+3 hours'), datetime('now', '-269 days', '+3 hours')),
(83, 2, 'Live sessions create real connections. Love this approach!', datetime('now', '-260 days', '+1 hour'), datetime('now', '-260 days', '+1 hour')),
(83, 6, 'Real-time interaction is powerful. Great engagement!', datetime('now', '-259 days'), datetime('now', '-259 days')),
(83, 10, 'Live content builds community. Well executed!', datetime('now', '-259 days', '+2 hours'), datetime('now', '-259 days', '+2 hours')),
(84, 2, 'Behind the scenes shows the real work. Love this transparency!', datetime('now', '-250 days', '+1 hour'), datetime('now', '-250 days', '+1 hour')),
(84, 6, 'Content creation is 80% strategy, 20% creation. Truth!', datetime('now', '-249 days'), datetime('now', '-249 days')),
(84, 14, 'Authentic content resonates. Great approach!', datetime('now', '-249 days', '+3 hours'), datetime('now', '-249 days', '+3 hours')),
(85, 2, 'TikTok challenges are so fun! Social media should be playful.', datetime('now', '-240 days', '+1 hour'), datetime('now', '-240 days', '+1 hour')),
(85, 6, 'Dance challenges bring joy to social media. Love it!', datetime('now', '-239 days'), datetime('now', '-239 days')),
(85, 15, 'Fun content creates viral moments. Well done!', datetime('now', '-239 days', '+2 hours'), datetime('now', '-239 days', '+2 hours')),
(86, 2, 'Brand partnerships that align with values are the best.', datetime('now', '-230 days', '+1 hour'), datetime('now', '-230 days', '+1 hour')),
(86, 6, 'Value-aligned partnerships create authentic content.', datetime('now', '-229 days'), datetime('now', '-229 days')),
(86, 10, 'Sustainable brand partnerships build trust.', datetime('now', '-229 days', '+3 hours'), datetime('now', '-229 days', '+3 hours')),

-- Comments on remaining posts (87-150) - distributed across various posts
(87, 1, 'Tech startup life is challenging but rewarding!', datetime('now', '-205 days', '+1 hour'), datetime('now', '-205 days', '+1 hour')),
(88, 5, 'Remote work productivity takes practice. Great tips!', datetime('now', '-195 days', '+1 hour'), datetime('now', '-195 days', '+1 hour')),
(89, 7, 'AI ethics discussions are crucial for responsible development.', datetime('now', '-200 days', '+1 hour'), datetime('now', '-200 days', '+1 hour')),
(90, 8, 'Machine learning fairness research is essential.', datetime('now', '-190 days', '+1 hour'), datetime('now', '-190 days', '+1 hour')),
(91, 9, 'Farm-to-table cooking celebrates fresh ingredients!', datetime('now', '-260 days', '+1 hour'), datetime('now', '-260 days', '+1 hour')),
(92, 11, 'Culinary fusion creates exciting flavor combinations.', datetime('now', '-250 days', '+1 hour'), datetime('now', '-250 days', '+1 hour')),
(93, 13, 'Teaching cooking skills empowers people in the kitchen.', datetime('now', '-240 days', '+1 hour'), datetime('now', '-240 days', '+1 hour')),
(94, 15, 'Investigative journalism uncovers important truths.', datetime('now', '-255 days', '+1 hour'), datetime('now', '-255 days', '+1 hour')),
(95, 17, 'Data journalism makes complex stories accessible.', datetime('now', '-245 days', '+1 hour'), datetime('now', '-245 days', '+1 hour')),
(96, 19, 'Press freedom is fundamental to democracy.', datetime('now', '-235 days', '+1 hour'), datetime('now', '-235 days', '+1 hour')),
(97, 21, 'Multimedia storytelling engages modern audiences.', datetime('now', '-225 days', '+1 hour'), datetime('now', '-225 days', '+1 hour')),
(98, 23, 'Community journalism connects local communities.', datetime('now', '-215 days', '+1 hour'), datetime('now', '-215 days', '+1 hour')),
(99, 25, 'Music composition is creative and technical mastery.', datetime('now', '-250 days', '+1 hour'), datetime('now', '-250 days', '+1 hour')),
(100, 27, 'Live performances create unforgettable experiences.', datetime('now', '-240 days', '+1 hour'), datetime('now', '-240 days', '+1 hour')),
(101, 29, 'Music production combines art and technology.', datetime('now', '-230 days', '+1 hour'), datetime('now', '-230 days', '+1 hour')),
(102, 1, 'Teacher appreciation recognizes important work.', datetime('now', '-245 days', '+1 hour'), datetime('now', '-245 days', '+1 hour')),
(103, 3, 'Project-based learning engages students deeply.', datetime('now', '-235 days', '+1 hour'), datetime('now', '-235 days', '+1 hour')),
(104, 5, 'STEM education prepares future innovators.', datetime('now', '-225 days', '+1 hour'), datetime('now', '-225 days', '+1 hour')),
(105, 7, 'Parent-teacher communication supports student success.', datetime('now', '-215 days', '+1 hour'), datetime('now', '-215 days', '+1 hour')),
(106, 9, 'Educational technology enhances learning experiences.', datetime('now', '-205 days', '+1 hour'), datetime('now', '-205 days', '+1 hour')),
(107, 11, 'Graduation celebrates achievement and growth.', datetime('now', '-195 days', '+1 hour'), datetime('now', '-195 days', '+1 hour')),
(108, 13, 'Sustainable architecture serves people and planet.', datetime('now', '-240 days', '+1 hour'), datetime('now', '-240 days', '+1 hour')),
(109, 15, 'Urban planning shapes livable communities.', datetime('now', '-230 days', '+1 hour'), datetime('now', '-230 days', '+1 hour')),
(110, 17, 'Historic preservation maintains cultural heritage.', datetime('now', '-220 days', '+1 hour'), datetime('now', '-220 days', '+1 hour')),
(111, 19, 'Mental health awareness reduces stigma.', datetime('now', '-235 days', '+1 hour'), datetime('now', '-235 days', '+1 hour')),
(112, 21, 'Therapy provides valuable support and healing.', datetime('now', '-225 days', '+1 hour'), datetime('now', '-225 days', '+1 hour')),
(113, 23, 'Software architecture enables scalable systems.', datetime('now', '-230 days', '+1 hour'), datetime('now', '-230 days', '+1 hour')),
(114, 25, 'System design interviews test problem-solving skills.', datetime('now', '-220 days', '+1 hour'), datetime('now', '-220 days', '+1 hour')),
(115, 27, 'Database optimization improves application performance.', datetime('now', '-210 days', '+1 hour'), datetime('now', '-210 days', '+1 hour')),
(116, 29, 'API design principles guide good interfaces.', datetime('now', '-200 days', '+1 hour'), datetime('now', '-200 days', '+1 hour')),
(117, 1, 'DevOps culture improves development processes.', datetime('now', '-190 days', '+1 hour'), datetime('now', '-190 days', '+1 hour')),
(118, 3, 'Graphic novels combine art and storytelling.', datetime('now', '-225 days', '+1 hour'), datetime('now', '-225 days', '+1 hour')),
(119, 5, 'Comic con celebrates creative communities.', datetime('now', '-215 days', '+1 hour'), datetime('now', '-215 days', '+1 hour')),
(120, 7, 'Visual storytelling conveys emotion powerfully.', datetime('now', '-205 days', '+1 hour'), datetime('now', '-205 days', '+1 hour')),
(121, 9, 'Color theory enhances visual communication.', datetime('now', '-195 days', '+1 hour'), datetime('now', '-195 days', '+1 hour')),
(122, 11, 'Self-publishing empowers creative control.', datetime('now', '-185 days', '+1 hour'), datetime('now', '-185 days', '+1 hour')),
(123, 13, 'Creative blocks are temporary challenges.', datetime('now', '-175 days', '+1 hour'), datetime('now', '-175 days', '+1 hour')),
(124, 15, 'Invention combines creativity and problem-solving.', datetime('now', '-220 days', '+1 hour'), datetime('now', '-220 days', '+1 hour')),
(125, 17, 'Engineering balances performance and sustainability.', datetime('now', '-210 days', '+1 hour'), datetime('now', '-210 days', '+1 hour')),
(126, 19, 'Patents protect innovative ideas.', datetime('now', '-200 days', '+1 hour'), datetime('now', '-200 days', '+1 hour')),
(127, 21, 'Global education connects diverse learners.', datetime('now', '-215 days', '+1 hour'), datetime('now', '-215 days', '+1 hour')),
(128, 23, 'Educational equity ensures fair opportunities.', datetime('now', '-205 days', '+1 hour'), datetime('now', '-205 days', '+1 hour')),
(129, 25, 'Teacher training improves educational quality.', datetime('now', '-195 days', '+1 hour'), datetime('now', '-195 days', '+1 hour')),
(130, 27, 'Digital literacy empowers modern citizens.', datetime('now', '-185 days', '+1 hour'), datetime('now', '-185 days', '+1 hour')),
(131, 29, 'Youth empowerment creates future leaders.', datetime('now', '-175 days', '+1 hour'), datetime('now', '-175 days', '+1 hour')),
(132, 1, 'Championship training demands dedication.', datetime('now', '-210 days', '+1 hour'), datetime('now', '-210 days', '+1 hour')),
(133, 3, 'Sports psychology enhances performance.', datetime('now', '-200 days', '+1 hour'), datetime('now', '-200 days', '+1 hour')),
(134, 5, 'Injury prevention maintains athlete health.', datetime('now', '-190 days', '+1 hour'), datetime('now', '-190 days', '+1 hour')),
(135, 7, 'Post-game recovery supports long-term success.', datetime('now', '-180 days', '+1 hour'), datetime('now', '-180 days', '+1 hour')),
(136, 9, 'Entrepreneurship requires persistence.', datetime('now', '-270 days', '+1 hour'), datetime('now', '-270 days', '+1 hour')),
(137, 11, 'Team building creates strong cultures.', datetime('now', '-260 days', '+1 hour'), datetime('now', '-260 days', '+1 hour')),
(138, 13, 'Product-market fit validates business models.', datetime('now', '-250 days', '+1 hour'), datetime('now', '-250 days', '+1 hour')),
(139, 15, 'Scaling challenges test business resilience.', datetime('now', '-240 days', '+1 hour'), datetime('now', '-240 days', '+1 hour')),
(140, 17, 'Climate research informs policy decisions.', datetime('now', '-265 days', '+1 hour'), datetime('now', '-265 days', '+1 hour')),
(141, 19, 'Environmental policy drives change.', datetime('now', '-255 days', '+1 hour'), datetime('now', '-255 days', '+1 hour')),
(142, 21, 'Renewable energy transforms power systems.', datetime('now', '-245 days', '+1 hour'), datetime('now', '-245 days', '+1 hour')),
(143, 23, 'Biodiversity conservation protects ecosystems.', datetime('now', '-235 days', '+1 hour'), datetime('now', '-235 days', '+1 hour')),
(144, 25, 'Carbon capture technology offers solutions.', datetime('now', '-225 days', '+1 hour'), datetime('now', '-225 days', '+1 hour')),
(145, 27, 'Youth climate activism inspires action.', datetime('now', '-215 days', '+1 hour'), datetime('now', '-215 days', '+1 hour')),
(146, 29, 'Chef skills celebrate culinary arts.', datetime('now', '-260 days', '+1 hour'), datetime('now', '-260 days', '+1 hour')),
(147, 1, 'Fusion cooking creates innovative dishes.', datetime('now', '-250 days', '+1 hour'), datetime('now', '-250 days', '+1 hour')),
(148, 3, 'Teaching empowers culinary confidence.', datetime('now', '-240 days', '+1 hour'), datetime('now', '-240 days', '+1 hour')),
(149, 5, 'Fashion design expresses personal style.', datetime('now', '-280 days', '+1 hour'), datetime('now', '-280 days', '+1 hour')),
-- Recent comments on new posts (151-200+) from users 31-40
(151, 1, 'Nathan, your AI research is groundbreaking! The UX implications are huge.', datetime('now', '-60 days'), datetime('now', '-60 days')),
(151, 2, 'Love seeing AI applied to user experience. What tools are you using?', datetime('now', '-59 days'), datetime('now', '-59 days')),
(151, 31, 'Thanks John! We''re using Figma with some custom ML models for user testing.', datetime('now', '-58 days'), datetime('now', '-58 days')),
(152, 3, 'Zoe, your biotech work sounds revolutionary. CRISPR applications are endless!', datetime('now', '-55 days'), datetime('now', '-55 days')),
(152, 32, 'Thanks Sarah! We''re working on gene therapies for rare diseases.', datetime('now', '-54 days'), datetime('now', '-54 days')),
(152, 5, 'The potential for personalized medicine is incredible. Keep up the great work!', datetime('now', '-53 days'), datetime('now', '-53 days')),
(153, 7, 'Carter, your DevOps automation is impressive. What''s your favorite tool?', datetime('now', '-50 days'), datetime('now', '-50 days')),
(153, 33, 'GitHub Actions and Terraform are game changers for infrastructure as code.', datetime('now', '-49 days'), datetime('now', '-49 days')),
(153, 13, 'Infrastructure as code is the future. Your approach is spot on!', datetime('now', '-48 days'), datetime('now', '-48 days')),
(154, 9, 'Luna, your research on neural interfaces is mind-blowing!', datetime('now', '-45 days'), datetime('now', '-45 days')),
(154, 34, 'Thanks Mike! Brain-computer interfaces will change everything.', datetime('now', '-44 days'), datetime('now', '-44 days')),
(154, 15, 'The ethical implications are fascinating. How do you approach user privacy?', datetime('now', '-43 days'), datetime('now', '-43 days')),
(155, 11, 'Aria, your sustainable architecture designs are beautiful and functional.', datetime('now', '-40 days'), datetime('now', '-40 days')),
(155, 35, 'Thanks Alice! Green building materials make such a difference.', datetime('now', '-39 days'), datetime('now', '-39 days')),
(155, 17, 'Love how you balance aesthetics with environmental responsibility.', datetime('now', '-38 days'), datetime('now', '-38 days')),
(156, 13, 'Jackson, your indie game development journey is inspiring!', datetime('now', '-35 days'), datetime('now', '-35 days')),
(156, 36, 'Thanks David! Unity and C# have been perfect for rapid prototyping.', datetime('now', '-34 days'), datetime('now', '-34 days')),
(156, 19, 'The narrative depth in your games is incredible. What inspires your stories?', datetime('now', '-33 days'), datetime('now', '-33 days')),
(157, 15, 'Scarlett, your social impact work is changing lives. Amazing!', datetime('now', '-30 days'), datetime('now', '-30 days')),
(157, 37, 'Thanks Emma! Community programs for at-risk youth are so rewarding.', datetime('now', '-29 days'), datetime('now', '-29 days')),
(157, 21, 'Your dedication to social justice is truly admirable.', datetime('now', '-28 days'), datetime('now', '-28 days')),
(158, 17, 'Mason, your data visualization work makes complex data accessible.', datetime('now', '-25 days'), datetime('now', '-25 days')),
(158, 38, 'Thanks James! D3.js and Python have been my go-to combo.', datetime('now', '-24 days'), datetime('now', '-24 days')),
(158, 23, 'Your charts tell such clear stories. Data storytelling at its best!', datetime('now', '-23 days'), datetime('now', '-23 days')),
(159, 19, 'Levi, your cybersecurity research is crucial in today''s world.', datetime('now', '-20 days'), datetime('now', '-20 days')),
(159, 39, 'Thanks Lisa! Zero-trust architecture is essential for modern security.', datetime('now', '-19 days'), datetime('now', '-19 days')),
(159, 25, 'How do you stay ahead of emerging threats? Your insights are valuable.', datetime('now', '-18 days'), datetime('now', '-18 days')),
(160, 21, 'Aiden, your AR/VR experiences are pushing creative boundaries!', datetime('now', '-15 days'), datetime('now', '-15 days')),
(160, 40, 'Thanks Ryan! Unreal Engine makes creating immersive worlds possible.', datetime('now', '-14 days'), datetime('now', '-14 days')),
(160, 27, 'The future of entertainment is here. Your work is visionary!', datetime('now', '-13 days'), datetime('now', '-13 days')),

-- More recent comments on various posts
(1, 31, 'React 18 concurrent features are still blowing my mind!', datetime('now', '-10 days'), datetime('now', '-10 days')),
(2, 32, 'Nature photography never gets old. Your composition is perfect.', datetime('now', '-8 days'), datetime('now', '-8 days')),
(3, 33, 'Go''s simplicity is deceptive - it''s incredibly powerful.', datetime('now', '-7 days'), datetime('now', '-7 days')),
(4, 34, 'AI startup journey looks challenging but rewarding!', datetime('now', '-6 days'), datetime('now', '-6 days')),
(5, 35, 'REST APIs in Go are so clean and efficient.', datetime('now', '-5 days'), datetime('now', '-5 days')),
(6, 36, 'Debugging strategies that actually work - thank you!', datetime('now', '-4 days'), datetime('now', '-4 days')),
(7, 37, 'Half marathon achievement is incredible! Congrats!', datetime('now', '-3 days'), datetime('now', '-3 days')),
(8, 38, 'JWT authentication done right. Security first!', datetime('now', '-2 days'), datetime('now', '-2 days')),
(9, 39, 'Coffee and coding - the universal developer experience.', datetime('now', '-1 day'), datetime('now', '-1 day')),

-- Comments on recent posts from existing users
(151, 32, 'The intersection of AI and UX design is fascinating. More please!', datetime('now', '-57 days'), datetime('now', '-57 days')),
(152, 33, 'Biotech breakthroughs give me hope for medical advancements.', datetime('now', '-52 days'), datetime('now', '-52 days')),
(153, 34, 'DevOps automation saves so much time. You''re doing important work.', datetime('now', '-47 days'), datetime('now', '-47 days')),
(154, 35, 'Neural interfaces could revolutionize accessibility technology.', datetime('now', '-42 days'), datetime('now', '-42 days')),
(155, 36, 'Sustainable architecture should be the standard, not the exception.', datetime('now', '-37 days'), datetime('now', '-37 days')),
(156, 37, 'Indie games often have the most creative and heartfelt stories.', datetime('now', '-32 days'), datetime('now', '-32 days')),
(157, 38, 'Social impact work like yours makes the world better.', datetime('now', '-27 days'), datetime('now', '-27 days')),
(158, 39, 'Data visualization that tells a story is worth a thousand charts.', datetime('now', '-22 days'), datetime('now', '-22 days')),
(159, 40, 'Cybersecurity awareness is more important than ever.', datetime('now', '-17 days'), datetime('now', '-17 days')),
(160, 31, 'AR/VR has so much potential for education and training.', datetime('now', '-12 days'), datetime('now', '-12 days'));