-- Mock Notifications Data
-- Creating realistic notifications for various user activities

INSERT INTO notifications (user_id, actor_id, type, entity_type, entity_id, title, message, is_read, created_at, updated_at) VALUES
-- Follow request notifications
(4, 2, 'follow_request', 'user', 2, 'New Follow Request', 'Sarah Wilson sent you a follow request', false, datetime('now', '-18 days'), datetime('now', '-18 days')),
(8, 10, 'follow_request', 'user', 10, 'New Follow Request', 'Sophia Lee sent you a follow request', true, datetime('now', '-12 hours'), datetime('now', '-12 hours')),
(12, 15, 'follow_request', 'user', 15, 'New Follow Request', 'Oliver Brown sent you a follow request', false, datetime('now', '-5 days'), datetime('now', '-5 days')),
(18, 22, 'follow_request', 'user', 22, 'New Follow Request', 'Zoe Martinez sent you a follow request', true, datetime('now', '-2 days'), datetime('now', '-2 days')),
(25, 28, 'follow_request', 'user', 28, 'New Follow Request', 'Lucas Thompson sent you a follow request', false, datetime('now', '-1 day'), datetime('now', '-1 day')),
(6, 9, 'follow_request', 'user', 9, 'New Follow Request', 'Ryan Garcia sent you a follow request', true, datetime('now', '-3 days'), datetime('now', '-3 days')),
(14, 17, 'follow_request', 'user', 17, 'New Follow Request', 'Ava Wilson sent you a follow request', false, datetime('now', '-7 days'), datetime('now', '-7 days')),
(21, 24, 'follow_request', 'user', 24, 'New Follow Request', 'Ethan Davis sent you a follow request', true, datetime('now', '-4 days'), datetime('now', '-4 days')),

-- Follow accepted notifications
(2, 4, 'follow_accepted', 'user', 4, 'Follow Request Accepted', 'Alice Cooper accepted your follow request', true, datetime('now', '-16 days'), datetime('now', '-16 days')),
(1, 7, 'follow_accepted', 'user', 7, 'New Follower', 'James Smith started following you', true, datetime('now', '-5 days'), datetime('now', '-5 days')),
(15, 12, 'follow_accepted', 'user', 12, 'Follow Request Accepted', 'Mia Johnson accepted your follow request', true, datetime('now', '-6 days'), datetime('now', '-6 days')),
(22, 18, 'follow_accepted', 'user', 18, 'Follow Request Accepted', 'Daniel Garcia accepted your follow request', false, datetime('now', '-3 days'), datetime('now', '-3 days')),
(28, 25, 'follow_accepted', 'user', 25, 'Follow Request Accepted', 'Harper Wilson accepted your follow request', true, datetime('now', '-2 days'), datetime('now', '-2 days')),
(9, 6, 'follow_accepted', 'user', 6, 'New Follower', 'Emma Davis started following you', false, datetime('now', '-4 days'), datetime('now', '-4 days')),
(17, 14, 'follow_accepted', 'user', 14, 'Follow Request Accepted', 'Noah Martinez accepted your follow request', true, datetime('now', '-8 days'), datetime('now', '-8 days')),
(24, 21, 'follow_accepted', 'user', 21, 'Follow Request Accepted', 'Isabella Thompson accepted your follow request', false, datetime('now', '-5 days'), datetime('now', '-5 days')),

-- New follower notifications
(1, 6, 'new_follower', 'user', 6, 'New Follower', 'Emma Davis started following you', true, datetime('now', '-10 days'), datetime('now', '-10 days')),
(2, 10, 'new_follower', 'user', 10, 'New Follower', 'Sophia Lee started following you', true, datetime('now', '-3 days'), datetime('now', '-3 days')),
(3, 8, 'new_follower', 'user', 8, 'New Follower', 'David Chen started following you', false, datetime('now', '-7 days'), datetime('now', '-7 days')),
(5, 11, 'new_follower', 'user', 11, 'New Follower', 'Liam Wilson started following you', true, datetime('now', '-6 days'), datetime('now', '-6 days')),
(7, 13, 'new_follower', 'user', 13, 'New Follower', 'Charlotte Lee started following you', false, datetime('now', '-9 days'), datetime('now', '-9 days')),
(9, 16, 'new_follower', 'user', 16, 'New Follower', 'Mason Davis started following you', true, datetime('now', '-4 days'), datetime('now', '-4 days')),
(11, 19, 'new_follower', 'user', 19, 'New Follower', 'Amelia Garcia started following you', false, datetime('now', '-8 days'), datetime('now', '-8 days')),
(13, 23, 'new_follower', 'user', 23, 'New Follower', 'Benjamin Wilson started following you', true, datetime('now', '-5 days'), datetime('now', '-5 days')),
(16, 26, 'new_follower', 'user', 26, 'New Follower', 'Evelyn Thompson started following you', false, datetime('now', '-3 days'), datetime('now', '-3 days')),
(19, 29, 'new_follower', 'user', 29, 'New Follower', 'Alexander Martinez started following you', true, datetime('now', '-2 days'), datetime('now', '-2 days')),
(20, 30, 'new_follower', 'user', 30, 'New Follower', 'Abigail Davis started following you', false, datetime('now', '-6 days'), datetime('now', '-6 days')),
(23, 27, 'new_follower', 'user', 27, 'New Follower', 'William Johnson started following you', true, datetime('now', '-7 days'), datetime('now', '-7 days')),

-- Post like notifications (distributed across posts 1-150)
(1, 2, 'post_liked', 'post', 1, 'Post Liked', 'Sarah Wilson liked your post', false, datetime('now', '-2 days', '+1 hour'), datetime('now', '-2 days', '+1 hour')),
(1, 3, 'post_liked', 'post', 1, 'Post Liked', 'Mike Johnson liked your post', false, datetime('now', '-2 days', '+2 hours'), datetime('now', '-2 days', '+2 hours')),
(1, 6, 'post_liked', 'post', 1, 'Post Liked', 'Emma Davis liked your post', false, datetime('now', '-1 day'), datetime('now', '-1 day')),
(2, 1, 'post_liked', 'post', 4, 'Post Liked', 'John Doe liked your post', true, datetime('now', '-1 day', '+30 minutes'), datetime('now', '-1 day', '+30 minutes')),
(3, 2, 'post_liked', 'post', 7, 'Post Liked', 'Sarah Wilson liked your post', false, datetime('now', '-1 day', '+2 hours'), datetime('now', '-1 day', '+2 hours')),
(4, 5, 'post_liked', 'post', 12, 'Post Liked', 'Olivia Martinez liked your post', true, datetime('now', '-3 days'), datetime('now', '-3 days')),
(5, 7, 'post_liked', 'post', 15, 'Post Liked', 'James Smith liked your post', false, datetime('now', '-2 days'), datetime('now', '-2 days')),
(6, 8, 'post_liked', 'post', 18, 'Post Liked', 'David Chen liked your post', true, datetime('now', '-4 days'), datetime('now', '-4 days')),
(7, 9, 'post_liked', 'post', 22, 'Post Liked', 'Ryan Garcia liked your post', false, datetime('now', '-1 day'), datetime('now', '-1 day')),
(8, 10, 'post_liked', 'post', 25, 'Post Liked', 'Sophia Lee liked your post', true, datetime('now', '-5 days'), datetime('now', '-5 days')),
(9, 11, 'post_liked', 'post', 28, 'Post Liked', 'Liam Wilson liked your post', false, datetime('now', '-3 days'), datetime('now', '-3 days')),
(10, 12, 'post_liked', 'post', 31, 'Post Liked', 'Mia Johnson liked your post', true, datetime('now', '-2 days'), datetime('now', '-2 days')),
(11, 13, 'post_liked', 'post', 35, 'Post Liked', 'Charlotte Lee liked your post', false, datetime('now', '-6 days'), datetime('now', '-6 days')),
(12, 14, 'post_liked', 'post', 38, 'Post Liked', 'Noah Martinez liked your post', true, datetime('now', '-4 days'), datetime('now', '-4 days')),
(13, 15, 'post_liked', 'post', 42, 'Post Liked', 'Oliver Brown liked your post', false, datetime('now', '-3 days'), datetime('now', '-3 days')),
(14, 16, 'post_liked', 'post', 45, 'Post Liked', 'Mason Davis liked your post', true, datetime('now', '-5 days'), datetime('now', '-5 days')),
(15, 17, 'post_liked', 'post', 48, 'Post Liked', 'Ava Wilson liked your post', false, datetime('now', '-2 days'), datetime('now', '-2 days')),
(16, 18, 'post_liked', 'post', 52, 'Post Liked', 'Daniel Garcia liked your post', true, datetime('now', '-7 days'), datetime('now', '-7 days')),
(17, 19, 'post_liked', 'post', 55, 'Post Liked', 'Amelia Garcia liked your post', false, datetime('now', '-4 days'), datetime('now', '-4 days')),
(18, 20, 'post_liked', 'post', 58, 'Post Liked', 'Lucas Thompson liked your post', true, datetime('now', '-3 days'), datetime('now', '-3 days')),
(19, 21, 'post_liked', 'post', 62, 'Post Liked', 'Isabella Thompson liked your post', false, datetime('now', '-6 days'), datetime('now', '-6 days')),
(20, 22, 'post_liked', 'post', 65, 'Post Liked', 'Zoe Martinez liked your post', true, datetime('now', '-2 days'), datetime('now', '-2 days')),
(21, 23, 'post_liked', 'post', 68, 'Post Liked', 'Benjamin Wilson liked your post', false, datetime('now', '-5 days'), datetime('now', '-5 days')),
(22, 24, 'post_liked', 'post', 72, 'Post Liked', 'Ethan Davis liked your post', true, datetime('now', '-4 days'), datetime('now', '-4 days')),
(23, 25, 'post_liked', 'post', 75, 'Post Liked', 'Harper Wilson liked your post', false, datetime('now', '-3 days'), datetime('now', '-3 days')),
(24, 26, 'post_liked', 'post', 78, 'Post Liked', 'Evelyn Thompson liked your post', true, datetime('now', '-7 days'), datetime('now', '-7 days')),
(25, 27, 'post_liked', 'post', 82, 'Post Liked', 'William Johnson liked your post', false, datetime('now', '-2 days'), datetime('now', '-2 days')),
(26, 28, 'post_liked', 'post', 85, 'Post Liked', 'Sofia Davis liked your post', true, datetime('now', '-6 days'), datetime('now', '-6 days')),
(27, 29, 'post_liked', 'post', 88, 'Post Liked', 'Alexander Martinez liked your post', false, datetime('now', '-4 days'), datetime('now', '-4 days')),
(28, 30, 'post_liked', 'post', 92, 'Post Liked', 'Abigail Davis liked your post', true, datetime('now', '-5 days'), datetime('now', '-5 days')),
(29, 1, 'post_liked', 'post', 95, 'Post Liked', 'John Doe liked your post', false, datetime('now', '-3 days'), datetime('now', '-3 days')),
(30, 3, 'post_liked', 'post', 98, 'Post Liked', 'Mike Johnson liked your post', true, datetime('now', '-2 days'), datetime('now', '-2 days')),

-- Comment notifications (distributed across posts)
(1, 4, 'comment', 'post', 1, 'New Comment', 'Alice Cooper commented on your post', false, datetime('now', '-2 days', '+3 hours'), datetime('now', '-2 days', '+3 hours')),
(1, 8, 'comment', 'post', 1, 'New Comment', 'David Chen commented on your post', true, datetime('now', '-1 day', '+4 hours'), datetime('now', '-1 day', '+4 hours')),
(2, 5, 'comment', 'post', 4, 'New Comment', 'Olivia Martinez commented on your post', false, datetime('now', '-1 day', '+1 hour'), datetime('now', '-1 day', '+1 hour')),
(3, 9, 'comment', 'post', 7, 'New Comment', 'Ryan Garcia commented on your post', true, datetime('now', '-1 day', '+3 hours'), datetime('now', '-1 day', '+3 hours')),
(4, 11, 'comment', 'post', 12, 'New Comment', 'Liam Wilson commented on your post', false, datetime('now', '-3 days', '+2 hours'), datetime('now', '-3 days', '+2 hours')),
(5, 13, 'comment', 'post', 15, 'New Comment', 'Charlotte Lee commented on your post', true, datetime('now', '-2 days', '+5 hours'), datetime('now', '-2 days', '+5 hours')),
(6, 15, 'comment', 'post', 18, 'New Comment', 'Oliver Brown commented on your post', false, datetime('now', '-4 days', '+1 hour'), datetime('now', '-4 days', '+1 hour')),
(7, 17, 'comment', 'post', 22, 'New Comment', 'Ava Wilson commented on your post', true, datetime('now', '-1 day', '+6 hours'), datetime('now', '-1 day', '+6 hours')),
(8, 19, 'comment', 'post', 25, 'New Comment', 'Amelia Garcia commented on your post', false, datetime('now', '-5 days', '+3 hours'), datetime('now', '-5 days', '+3 hours')),
(9, 21, 'comment', 'post', 28, 'New Comment', 'Isabella Thompson commented on your post', true, datetime('now', '-3 days', '+4 hours'), datetime('now', '-3 days', '+4 hours')),
(10, 23, 'comment', 'post', 31, 'New Comment', 'Benjamin Wilson commented on your post', false, datetime('now', '-2 days', '+2 hours'), datetime('now', '-2 days', '+2 hours')),
(11, 25, 'comment', 'post', 35, 'New Comment', 'Harper Wilson commented on your post', true, datetime('now', '-6 days', '+1 hour'), datetime('now', '-6 days', '+1 hour')),
(12, 27, 'comment', 'post', 38, 'New Comment', 'William Johnson commented on your post', false, datetime('now', '-4 days', '+5 hours'), datetime('now', '-4 days', '+5 hours')),
(13, 29, 'comment', 'post', 42, 'New Comment', 'Alexander Martinez commented on your post', true, datetime('now', '-3 days', '+6 hours'), datetime('now', '-3 days', '+6 hours')),
(14, 2, 'comment', 'post', 45, 'New Comment', 'Sarah Wilson commented on your post', false, datetime('now', '-5 days', '+2 hours'), datetime('now', '-5 days', '+2 hours')),
(15, 4, 'comment', 'post', 48, 'New Comment', 'Alice Cooper commented on your post', true, datetime('now', '-2 days', '+7 hours'), datetime('now', '-2 days', '+7 hours')),
(16, 6, 'comment', 'post', 52, 'New Comment', 'Emma Davis commented on your post', false, datetime('now', '-7 days', '+3 hours'), datetime('now', '-7 days', '+3 hours')),
(17, 8, 'comment', 'post', 55, 'New Comment', 'David Chen commented on your post', true, datetime('now', '-4 days', '+4 hours'), datetime('now', '-4 days', '+4 hours')),
(18, 10, 'comment', 'post', 58, 'New Comment', 'Sophia Lee commented on your post', false, datetime('now', '-3 days', '+1 hour'), datetime('now', '-3 days', '+1 hour')),
(19, 12, 'comment', 'post', 62, 'New Comment', 'Mia Johnson commented on your post', true, datetime('now', '-6 days', '+5 hours'), datetime('now', '-6 days', '+5 hours')),
(20, 14, 'comment', 'post', 65, 'New Comment', 'Noah Martinez commented on your post', false, datetime('now', '-2 days', '+3 hours'), datetime('now', '-2 days', '+3 hours')),
(21, 16, 'comment', 'post', 68, 'New Comment', 'Mason Davis commented on your post', true, datetime('now', '-5 days', '+6 hours'), datetime('now', '-5 days', '+6 hours')),
(22, 18, 'comment', 'post', 72, 'New Comment', 'Daniel Garcia commented on your post', false, datetime('now', '-4 days', '+2 hours'), datetime('now', '-4 days', '+2 hours')),
(23, 20, 'comment', 'post', 75, 'New Comment', 'Lucas Thompson commented on your post', true, datetime('now', '-3 days', '+7 hours'), datetime('now', '-3 days', '+7 hours')),
(24, 22, 'comment', 'post', 78, 'New Comment', 'Zoe Martinez commented on your post', false, datetime('now', '-7 days', '+1 hour'), datetime('now', '-7 days', '+1 hour')),
(25, 24, 'comment', 'post', 82, 'New Comment', 'Ethan Davis commented on your post', true, datetime('now', '-2 days', '+4 hours'), datetime('now', '-2 days', '+4 hours')),
(26, 26, 'comment', 'post', 85, 'New Comment', 'Evelyn Thompson commented on your post', false, datetime('now', '-6 days', '+2 hours'), datetime('now', '-6 days', '+2 hours')),
(27, 28, 'comment', 'post', 88, 'New Comment', 'Sofia Davis commented on your post', true, datetime('now', '-4 days', '+7 hours'), datetime('now', '-4 days', '+7 hours')),
(28, 30, 'comment', 'post', 92, 'New Comment', 'Abigail Davis commented on your post', false, datetime('now', '-5 days', '+3 hours'), datetime('now', '-5 days', '+3 hours')),
(29, 3, 'comment', 'post', 95, 'New Comment', 'Mike Johnson commented on your post', true, datetime('now', '-3 days', '+5 hours'), datetime('now', '-3 days', '+5 hours')),
(30, 5, 'comment', 'post', 98, 'New Comment', 'Olivia Martinez commented on your post', false, datetime('now', '-2 days', '+6 hours'), datetime('now', '-2 days', '+6 hours')),

-- Group invitation notifications
(2, 7, 'group_invitation', 'group', 2, 'Group Invitation', 'You were invited to join "Go Language Enthusiasts"', true, datetime('now', '-5 days'), datetime('now', '-5 days')),
(9, 4, 'group_invitation', 'group', 7, 'Group Invitation', 'You were invited to join "Digital Art Collective"', false, datetime('now', '-3 days'), datetime('now', '-3 days')),
(2, 5, 'group_invitation', 'group', 8, 'Group Invitation', 'You were invited to join "Startup Founders Network"', false, datetime('now', '-2 days'), datetime('now', '-2 days')),
(15, 12, 'group_invitation', 'group', 3, 'Group Invitation', 'You were invited to join "Photography Enthusiasts"', true, datetime('now', '-4 days'), datetime('now', '-4 days')),
(22, 18, 'group_invitation', 'group', 5, 'Group Invitation', 'You were invited to join "Book Club Monthly"', false, datetime('now', '-6 days'), datetime('now', '-6 days')),
(28, 25, 'group_invitation', 'group', 9, 'Group Invitation', 'You were invited to join "Fitness & Wellness"', true, datetime('now', '-3 days'), datetime('now', '-3 days')),
(6, 9, 'group_invitation', 'group', 1, 'Group Invitation', 'You were invited to join "React Developers Community"', false, datetime('now', '-5 days'), datetime('now', '-5 days')),
(14, 17, 'group_invitation', 'group', 4, 'Group Invitation', 'You were invited to join "Machine Learning Practitioners"', true, datetime('now', '-7 days'), datetime('now', '-7 days')),

-- Group join request notifications (for admins)
(7, 2, 'group_join_request', 'group', 2, 'Join Request', 'Sarah Wilson requested to join "Go Language Enthusiasts"', false, datetime('now', '-5 days'), datetime('now', '-5 days')),
(4, 9, 'group_join_request', 'group', 7, 'Join Request', 'Ryan Garcia requested to join "Digital Art Collective"', false, datetime('now', '-3 days'), datetime('now', '-3 days')),
(5, 2, 'group_join_request', 'group', 8, 'Join Request', 'Sarah Wilson requested to join "Startup Founders Network"', false, datetime('now', '-2 days'), datetime('now', '-2 days')),
(12, 15, 'group_join_request', 'group', 3, 'Join Request', 'Oliver Brown requested to join "Photography Enthusiasts"', true, datetime('now', '-4 days'), datetime('now', '-4 days')),
(18, 22, 'group_join_request', 'group', 5, 'Join Request', 'Zoe Martinez requested to join "Book Club Monthly"', false, datetime('now', '-6 days'), datetime('now', '-6 days')),
(25, 28, 'group_join_request', 'group', 9, 'Join Request', 'Lucas Thompson requested to join "Fitness & Wellness"', true, datetime('now', '-3 days'), datetime('now', '-3 days')),
(1, 6, 'group_join_request', 'group', 1, 'Join Request', 'Emma Davis requested to join "React Developers Community"', false, datetime('now', '-5 days'), datetime('now', '-5 days')),
(16, 19, 'group_join_request', 'group', 4, 'Join Request', 'Amelia Garcia requested to join "Machine Learning Practitioners"', true, datetime('now', '-7 days'), datetime('now', '-7 days')),

-- Event notifications
(1, NULL, 'event_reminder', 'event', 1, 'Event Reminder', 'Reminder: "React 18 Workshop" starts in 2 days', false, datetime('now', '-2 days'), datetime('now', '-2 days')),
(2, NULL, 'event_reminder', 'event', 1, 'Event Reminder', 'Reminder: "React 18 Workshop" starts in 2 days', false, datetime('now', '-2 days'), datetime('now', '-2 days')),
(3, NULL, 'event_reminder', 'event', 6, 'Event Reminder', 'Reminder: "Group Training Session" starts tomorrow', false, datetime('now', '-1 day'), datetime('now', '-1 day')),
(6, NULL, 'event_reminder', 'event', 4, 'Event Reminder', 'Reminder: "Design System Workshop" starts in 3 days', false, datetime('now', '-2 days'), datetime('now', '-2 days')),
(8, NULL, 'event_reminder', 'event', 2, 'Event Reminder', 'Reminder: "Code Review Session" starts tomorrow', true, datetime('now', '-1 day'), datetime('now', '-1 day')),
(12, NULL, 'event_reminder', 'event', 3, 'Event Reminder', 'Reminder: "Photography Meetup" starts in 2 days', false, datetime('now', '-2 days'), datetime('now', '-2 days')),
(15, NULL, 'event_reminder', 'event', 5, 'Event Reminder', 'Reminder: "Book Discussion" starts tomorrow', true, datetime('now', '-1 day'), datetime('now', '-1 day')),
(20, NULL, 'event_reminder', 'event', 7, 'Event Reminder', 'Reminder: "AI Ethics Panel" starts in 3 days', false, datetime('now', '-2 days'), datetime('now', '-2 days')),

-- New event notifications
(1, 5, 'new_event', 'event', 2, 'New Event', 'New event "Code Review Session" was created in React Developers Community', true, datetime('now', '-3 days'), datetime('now', '-3 days')),
(6, 6, 'new_event', 'event', 5, 'New Event', 'New event "Accessibility in Design Panel" was created in UI/UX Designers Network', false, datetime('now', '-1 day'), datetime('now', '-1 day')),
(12, 12, 'new_event', 'event', 3, 'New Event', 'New event "Photography Meetup" was created in Photography Enthusiasts', true, datetime('now', '-4 days'), datetime('now', '-4 days')),
(18, 18, 'new_event', 'event', 6, 'New Event', 'New event "Group Training Session" was created in Fitness & Wellness', false, datetime('now', '-2 days'), datetime('now', '-2 days')),
(25, 25, 'new_event', 'event', 8, 'New Event', 'New event "Startup Pitch Night" was created in Startup Founders Network', true, datetime('now', '-5 days'), datetime('now', '-5 days')),

-- Event response notifications
(5, 1, 'event_response', 'event', 1, 'Event Response', 'John Doe is going to "React 18 Workshop"', false, datetime('now', '-3 days'), datetime('now', '-3 days')),
(5, 2, 'event_response', 'event', 1, 'Event Response', 'Sarah Wilson is going to "React 18 Workshop"', true, datetime('now', '-3 days'), datetime('now', '-3 days')),
(6, 8, 'event_response', 'event', 4, 'Event Response', 'David Chen is not going to "Design System Workshop"', false, datetime('now', '-4 days'), datetime('now', '-4 days')),
(12, 15, 'event_response', 'event', 3, 'Event Response', 'Oliver Brown is going to "Photography Meetup"', true, datetime('now', '-5 days'), datetime('now', '-5 days')),
(18, 22, 'event_response', 'event', 6, 'Event Response', 'Zoe Martinez is going to "Group Training Session"', false, datetime('now', '-3 days'), datetime('now', '-3 days')),

-- Message notifications
(2, 1, 'new_message', 'message', NULL, 'New Message', 'You have a new message from John Doe', true, datetime('now', '-2 days', '+11:00'), datetime('now', '-2 days', '+11:00')),
(1, 2, 'new_message', 'message', NULL, 'New Message', 'You have a new message from Sarah Wilson', true, datetime('now', '-2 days', '+11:15'), datetime('now', '-2 days', '+11:15')),
(5, 3, 'new_message', 'message', NULL, 'New Message', 'You have a new message from Mike Johnson', false, datetime('now', '-1 day', '+14:00'), datetime('now', '-1 day', '+14:00')),
(9, 7, 'new_message', 'message', NULL, 'New Message', 'You have a new message from James Smith', false, datetime('now', '-12 hours'), datetime('now', '-12 hours')),
(12, 15, 'new_message', 'message', NULL, 'New Message', 'You have a new message from Oliver Brown', true, datetime('now', '-1 day', '+10:00'), datetime('now', '-1 day', '+10:00')),
(18, 22, 'new_message', 'message', NULL, 'New Message', 'You have a new message from Zoe Martinez', false, datetime('now', '-3 hours'), datetime('now', '-3 hours')),
(25, 28, 'new_message', 'message', NULL, 'New Message', 'You have a new message from Lucas Thompson', true, datetime('now', '-6 hours'), datetime('now', '-6 hours')),
(6, 9, 'new_message', 'message', NULL, 'New Message', 'You have a new message from Ryan Garcia', false, datetime('now', '-2 days', '+9:00'), datetime('now', '-2 days', '+9:00')),
(14, 17, 'new_message', 'message', NULL, 'New Message', 'You have a new message from Ava Wilson', true, datetime('now', '-1 day', '+16:00'), datetime('now', '-1 day', '+16:00')),
(21, 24, 'new_message', 'message', NULL, 'New Message', 'You have a new message from Ethan Davis', false, datetime('now', '-4 hours'), datetime('now', '-4 hours')),

-- Group message notifications
(1, 2, 'group_message', 'group', 1, 'New Group Message', 'New message in React Developers Community', true, datetime('now', '-3 days'), datetime('now', '-3 days')),
(2, 3, 'group_message', 'group', 2, 'New Group Message', 'New message in Go Language Enthusiasts', false, datetime('now', '-8 days'), datetime('now', '-8 days')),
(4, 8, 'group_message', 'group', 3, 'New Group Message', 'New message in UI/UX Designers Network', false, datetime('now', '-5 days'), datetime('now', '-5 days')),
(12, 15, 'group_message', 'group', 3, 'New Group Message', 'New message in Photography Enthusiasts', true, datetime('now', '-4 days'), datetime('now', '-4 days')),
(18, 22, 'group_message', 'group', 5, 'New Group Message', 'New message in Book Club Monthly', false, datetime('now', '-6 days'), datetime('now', '-6 days')),
(25, 28, 'group_message', 'group', 9, 'New Group Message', 'New message in Fitness & Wellness', true, datetime('now', '-3 days'), datetime('now', '-3 days')),
(6, 9, 'group_message', 'group', 4, 'New Group Message', 'New message in Machine Learning Practitioners', false, datetime('now', '-7 days'), datetime('now', '-7 days')),
(14, 17, 'group_message', 'group', 7, 'New Group Message', 'New message in Digital Art Collective', true, datetime('now', '-5 days'), datetime('now', '-5 days')),

-- Activity notifications
(1, NULL, 'weekly_summary', 'system', NULL, 'Weekly Summary', 'Your weekly activity summary is ready! You had 15 interactions this week', true, datetime('now', '-7 days'), datetime('now', '-7 days')),
(3, NULL, 'achievement', 'system', NULL, 'Achievement', 'Congratulations! You reached 50 followers', true, datetime('now', '-5 days'), datetime('now', '-5 days')),
(9, NULL, 'achievement', 'post', 25, 'Achievement', 'Your post received 10 likes!', false, datetime('now', '-1 day', '+5 hours'), datetime('now', '-1 day', '+5 hours')),
(15, NULL, 'achievement', 'user', NULL, 'Achievement', 'Congratulations! You reached 100 followers', true, datetime('now', '-3 days'), datetime('now', '-3 days')),
(22, NULL, 'achievement', 'post', 75, 'Achievement', 'Your post received 25 likes!', false, datetime('now', '-2 days'), datetime('now', '-2 days')),
(28, NULL, 'achievement', 'system', NULL, 'Achievement', 'You have been active for 6 months!', true, datetime('now', '-1 day'), datetime('now', '-1 day')),
(6, NULL, 'weekly_summary', 'system', NULL, 'Weekly Summary', 'Your weekly activity summary is ready! You had 8 interactions this week', false, datetime('now', '-7 days'), datetime('now', '-7 days')),
(14, NULL, 'achievement', 'post', 45, 'Achievement', 'Your post received 15 likes!', true, datetime('now', '-4 days'), datetime('now', '-4 days')),
(21, NULL, 'achievement', 'user', NULL, 'Achievement', 'Congratulations! You reached 75 followers', false, datetime('now', '-5 days'), datetime('now', '-5 days')),
(29, NULL, 'weekly_summary', 'system', NULL, 'Weekly Summary', 'Your weekly activity summary is ready! You had 22 interactions this week', true, datetime('now', '-7 days'), datetime('now', '-7 days')),
(4, 7, 'post_liked', 'post', 101, 'Post Liked', 'James Smith liked your post', false, datetime('now', '-6 days'), datetime('now', '-6 days')),
(7, 10, 'post_liked', 'post', 105, 'Post Liked', 'Sophia Lee liked your post', true, datetime('now', '-5 days'), datetime('now', '-5 days')),
(10, 13, 'post_liked', 'post', 108, 'Post Liked', 'Charlotte Lee liked your post', false, datetime('now', '-4 days'), datetime('now', '-4 days')),
(13, 16, 'post_liked', 'post', 112, 'Post Liked', 'Mason Davis liked your post', true, datetime('now', '-7 days'), datetime('now', '-7 days')),
(16, 19, 'post_liked', 'post', 115, 'Post Liked', 'Amelia Garcia liked your post', false, datetime('now', '-3 days'), datetime('now', '-3 days')),
(19, 22, 'post_liked', 'post', 118, 'Post Liked', 'Zoe Martinez liked your post', true, datetime('now', '-6 days'), datetime('now', '-6 days')),
(22, 25, 'post_liked', 'post', 122, 'Post Liked', 'Harper Wilson liked your post', false, datetime('now', '-5 days'), datetime('now', '-5 days')),
(25, 28, 'post_liked', 'post', 125, 'Post Liked', 'Sofia Davis liked your post', true, datetime('now', '-4 days'), datetime('now', '-4 days')),
(28, 1, 'post_liked', 'post', 128, 'Post Liked', 'John Doe liked your post', false, datetime('now', '-7 days'), datetime('now', '-7 days')),
(1, 4, 'post_liked', 'post', 132, 'Post Liked', 'Alice Cooper liked your post', true, datetime('now', '-3 days'), datetime('now', '-3 days')),
(4, 7, 'post_liked', 'post', 135, 'Post Liked', 'James Smith liked your post', false, datetime('now', '-6 days'), datetime('now', '-6 days')),
(7, 10, 'post_liked', 'post', 138, 'Post Liked', 'Sophia Lee liked your post', true, datetime('now', '-5 days'), datetime('now', '-5 days')),
(10, 13, 'post_liked', 'post', 142, 'Post Liked', 'Charlotte Lee liked your post', false, datetime('now', '-4 days'), datetime('now', '-4 days')),
(13, 16, 'post_liked', 'post', 145, 'Post Liked', 'Mason Davis liked your post', true, datetime('now', '-7 days'), datetime('now', '-7 days')),
(16, 19, 'post_liked', 'post', 148, 'Post Liked', 'Amelia Garcia liked your post', false, datetime('now', '-3 days'), datetime('now', '-3 days')),
(19, 22, 'post_liked', 'post', 150, 'Post Liked', 'Zoe Martinez liked your post', true, datetime('now', '-6 days'), datetime('now', '-6 days')),
(3, 6, 'comment', 'post', 102, 'New Comment', 'Emma Davis commented on your post', false, datetime('now', '-6 days', '+2 hours'), datetime('now', '-6 days', '+2 hours')),
(6, 9, 'comment', 'post', 106, 'New Comment', 'Ryan Garcia commented on your post', true, datetime('now', '-5 days', '+3 hours'), datetime('now', '-5 days', '+3 hours')),
(9, 12, 'comment', 'post', 109, 'New Comment', 'Mia Johnson commented on your post', false, datetime('now', '-4 days', '+1 hour'), datetime('now', '-4 days', '+1 hour')),
(12, 15, 'comment', 'post', 113, 'New Comment', 'Oliver Brown commented on your post', true, datetime('now', '-7 days', '+4 hours'), datetime('now', '-7 days', '+4 hours')),
(15, 18, 'comment', 'post', 116, 'New Comment', 'Daniel Garcia commented on your post', false, datetime('now', '-3 days', '+2 hours'), datetime('now', '-3 days', '+2 hours')),
(18, 21, 'comment', 'post', 119, 'New Comment', 'Isabella Thompson commented on your post', true, datetime('now', '-6 days', '+5 hours'), datetime('now', '-6 days', '+5 hours')),
(21, 24, 'comment', 'post', 123, 'New Comment', 'Ethan Davis commented on your post', false, datetime('now', '-5 days', '+3 hours'), datetime('now', '-5 days', '+3 hours')),
(24, 27, 'comment', 'post', 126, 'New Comment', 'William Johnson commented on your post', true, datetime('now', '-4 days', '+6 hours'), datetime('now', '-4 days', '+6 hours')),
(27, 30, 'comment', 'post', 129, 'New Comment', 'Abigail Davis commented on your post', false, datetime('now', '-7 days', '+1 hour'), datetime('now', '-7 days', '+1 hour')),
(30, 3, 'comment', 'post', 133, 'New Comment', 'Mike Johnson commented on your post', true, datetime('now', '-3 days', '+4 hours'), datetime('now', '-3 days', '+4 hours')),
(2, 5, 'comment', 'post', 136, 'New Comment', 'Olivia Martinez commented on your post', false, datetime('now', '-6 days', '+7 hours'), datetime('now', '-6 days', '+7 hours')),
(5, 8, 'comment', 'post', 139, 'New Comment', 'David Chen commented on your post', true, datetime('now', '-5 days', '+2 hours'), datetime('now', '-5 days', '+2 hours')),
(8, 11, 'comment', 'post', 143, 'New Comment', 'Liam Wilson commented on your post', false, datetime('now', '-4 days', '+5 hours'), datetime('now', '-4 days', '+5 hours')),
(11, 14, 'comment', 'post', 146, 'New Comment', 'Noah Martinez commented on your post', true, datetime('now', '-7 days', '+3 hours'), datetime('now', '-7 days', '+3 hours')),
(14, 17, 'comment', 'post', 149, 'New Comment', 'Ava Wilson commented on your post', false, datetime('now', '-3 days', '+6 hours'), datetime('now', '-3 days', '+6 hours')),
(17, 20, 'comment', 'post', 150, 'New Comment', 'Lucas Thompson commented on your post', true, datetime('now', '-6 days', '+4 hours'), datetime('now', '-6 days', '+4 hours')),
(1, 3, 'new_follower', 'user', 3, 'New Follower', 'Mike Johnson started following you', false, datetime('now', '-8 days'), datetime('now', '-8 days')),
(3, 5, 'new_follower', 'user', 5, 'New Follower', 'Olivia Martinez started following you', true, datetime('now', '-9 days'), datetime('now', '-9 days')),
(5, 8, 'new_follower', 'user', 8, 'New Follower', 'David Chen started following you', false, datetime('now', '-7 days'), datetime('now', '-7 days')),
(8, 11, 'new_follower', 'user', 11, 'New Follower', 'Liam Wilson started following you', true, datetime('now', '-6 days'), datetime('now', '-6 days')),
(11, 14, 'new_follower', 'user', 14, 'New Follower', 'Noah Martinez started following you', false, datetime('now', '-8 days'), datetime('now', '-8 days')),
(14, 17, 'new_follower', 'user', 17, 'New Follower', 'Ava Wilson started following you', true, datetime('now', '-5 days'), datetime('now', '-5 days')),
(17, 20, 'new_follower', 'user', 20, 'New Follower', 'Lucas Thompson started following you', false, datetime('now', '-9 days'), datetime('now', '-9 days')),
(20, 23, 'new_follower', 'user', 23, 'New Follower', 'Benjamin Wilson started following you', true, datetime('now', '-7 days'), datetime('now', '-7 days')),
(23, 26, 'new_follower', 'user', 26, 'New Follower', 'Evelyn Thompson started following you', false, datetime('now', '-6 days'), datetime('now', '-6 days')),
(26, 29, 'new_follower', 'user', 29, 'New Follower', 'Alexander Martinez started following you', true, datetime('now', '-8 days'), datetime('now', '-8 days')),
(4, 6, 'follow_request', 'user', 6, 'New Follow Request', 'Emma Davis sent you a follow request', false, datetime('now', '-10 days'), datetime('now', '-10 days')),
(7, 9, 'follow_request', 'user', 9, 'New Follow Request', 'Ryan Garcia sent you a follow request', true, datetime('now', '-9 days'), datetime('now', '-9 days')),
(10, 12, 'follow_request', 'user', 12, 'New Follow Request', 'Mia Johnson sent you a follow request', false, datetime('now', '-8 days'), datetime('now', '-8 days')),
(13, 15, 'follow_request', 'user', 15, 'New Follow Request', 'Oliver Brown sent you a follow request', true, datetime('now', '-7 days'), datetime('now', '-7 days')),
(16, 18, 'follow_request', 'user', 18, 'New Follow Request', 'Daniel Garcia sent you a follow request', false, datetime('now', '-6 days'), datetime('now', '-6 days'));
