

INSERT INTO users (email, password, first_name, last_name, date_of_birth, avatar, nickname, about_me, is_private, created_at, updated_at) VALUES
('john.doe@example.com', '$2a$10$RHttySZHDbKUw9e9FQlWIOxf6wFyF02NoPdPpJxKLWoj/D9HZjSrq', 'John', 'Doe', '1990-05-15', 'https://api.dicebear.com/7.x/avataaars/svg?seed=john_doe&backgroundColor=b6e3f4', 'johndoe', 'Software engineer passionate about technology and innovation. Love to code and explore new frameworks!', false, datetime('now', '-30 days'), datetime('now', '-1 day')),
('sarah.wilson@example.com', '$2a$10$RHttySZHDbKUw9e9FQlWIOxf6wFyF02NoPdPpJxKLWoj/D9HZjSrq', 'Sarah', 'Wilson', '1992-08-22', 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah_wilson&backgroundColor=c0aede', 'sarahw', 'Digital marketing specialist. Travel enthusiast and coffee lover ☕ Always looking for the next adventure!', false, datetime('now', '-25 days'), datetime('now', '-2 hours')),
('mike.johnson@example.com', '$2a$10$RHttySZHDbKUw9e9FQlWIOxf6wFyF02NoPdPpJxKLWoj/D9HZjSrq', 'Mike', 'Johnson', '1988-12-03', 'https://api.dicebear.com/7.x/avataaars/svg?seed=mike_johnson&backgroundColor=a3bf9b', 'mikej', 'Fitness trainer and nutrition coach. Helping people achieve their health goals 💪 #FitLife #HealthyLiving', false, datetime('now', '-20 days'), datetime('now', '-1 hour')),
('alice.cooper@example.com', '$2a$10$RHttySZHDbKUw9e9FQlWIOxf6wFyF02NoPdPpJxKLWoj/D9HZjSrq', 'Alice', 'Cooper', '1995-03-10', 'https://api.dicebear.com/7.x/avataaars/svg?seed=alice_cooper&backgroundColor=f4a261', 'alicecooper', 'Graphic designer and artist. Creating beautiful designs that tell stories 🎨 Portfolio: alice-designs.com', true, datetime('now', '-18 days'), datetime('now', '-30 minutes')),
('david.brown@example.com', '$2a$10$RHttySZHDbKUw9e9FQlWIOxf6wFyF02NoPdPpJxKLWoj/D9HZjSrq', 'David', 'Brown', '1987-11-28', 'https://api.dicebear.com/7.x/avataaars/svg?seed=david_brown&backgroundColor=81c3d7', 'davidb', 'Product manager at tech startup. Love building products that make a difference 🚀 Currently working on AI solutions', false, datetime('now', '-15 days'), datetime('now', '-45 minutes')),
('emma.davis@example.com', '$2a$10$RHttySZHDbKUw9e9FQlWIOxf6wFyF02NoPdPpJxKLWoj/D9HZjSrq', 'Emma', 'Davis', '1993-07-14', 'https://api.dicebear.com/7.x/avataaars/svg?seed=emma_davis&backgroundColor=e9c46a', 'emmad', 'UX/UI designer focusing on accessible design. Making the web better for everyone 🌐 Accessibility advocate', false, datetime('now', '-12 days'), datetime('now', '-15 minutes')),
('james.smith@example.com', '$2a$10$RHttySZHDbKUw9e9FQlWIOxf6wFyF02NoPdPpJxKLWoj/D9HZjSrq', 'James', 'Smith', '1991-01-20', 'https://api.dicebear.com/7.x/avataaars/svg?seed=james_smith&backgroundColor=f4a688', 'jamessmith', 'Full-stack developer and open source contributor. Building the future one commit at a time 👨‍💻', false, datetime('now', '-10 days'), datetime('now', '-5 minutes')),
('lisa.taylor@example.com', '$2a$10$RHttySZHDbKUw9e9FQlWIOxf6wFyF02NoPdPpJxKLWoj/D9HZjSrq', 'Lisa', 'Taylor', '1994-09-05', 'https://api.dicebear.com/7.x/avataaars/svg?seed=lisa_taylor&backgroundColor=b8c5d6', 'lisat', 'Data scientist and machine learning engineer. Turning data into insights 📊 PhD in Computer Science', true, datetime('now', '-8 days'), datetime('now', '-10 minutes')),
('ryan.garcia@example.com', '$2a$10$RHttySZHDbKUw9e9FQlWIOxf6wFyF02NoPdPpJxKLWoj/D9HZjSrq', 'Ryan', 'Garcia', '1989-06-18', 'https://api.dicebear.com/7.x/avataaars/svg?seed=ryan_garcia&backgroundColor=dda0dd', 'ryang', 'Photographer and videographer. Capturing life''s beautiful moments 📸 Available for events and portraits', false, datetime('now', '-7 days'), datetime('now', '-20 minutes')),
('sophia.lee@example.com', '$2a$10$RHttySZHDbKUw9e9FQlWIOxf6wFyF02NoPdPpJxKLWoj/D9HZjSrq', 'Sophia', 'Lee', '1996-04-12', 'https://api.dicebear.com/7.x/avataaars/svg?seed=sophia_lee&backgroundColor=98d8c8', 'sophial', 'Marketing coordinator and content creator. Storytelling through social media ✨ #ContentCreator #Marketing', false, datetime('now', '-5 days'), datetime('now', '-3 minutes')),
('oliver.martin@example.com', '$2a$10$RHttySZHDbKUw9e9FQlWIOxf6wFyF02NoPdPpJxKLWoj/D9HZjSrq', 'Oliver', 'Martin', '1985-02-28', 'https://api.dicebear.com/7.x/avataaars/svg?seed=oliver_martin&backgroundColor=f7dc6f', 'oliverm', 'Financial analyst and investor. Sharing tips on personal finance and investing. #Finance #Investing', false, datetime('now', '-4 days'), datetime('now', '-2 minutes')),
('mia.hernandez@example.com', '$2a$10$RHttySZHDbKUw9e9FQlWIOxf6wFyF02NoPdPpJxKLWoj/D9HZjSrq', 'Mia', 'Hernandez', '1997-11-03', 'https://api.dicebear.com/7.x/avataaars/svg?seed=mia_hernandez&backgroundColor=bb8fce', 'miahernandez', 'Veterinarian and animal lover. Advice on pet care and animal health 🐾', true, datetime('now', '-3 days'), datetime('now', '-1 minute')),
('ethan.wang@example.com', '$2a$10$RHttySZHDbKUw9e9FQlWIOxf6wFyF02NoPdPpJxKLWoj/D9HZjSrq', 'Ethan', 'Wang', '1992-06-21', 'https://api.dicebear.com/7.x/avataaars/svg?seed=ethan_wang&backgroundColor=85c1e9', 'ethanwang', 'Science communicator and researcher. Making science accessible to everyone! #Science #Education', false, datetime('now', '-2 days'), datetime('now', '-1 minute')),
('chloe.bennett@example.com', '$2a$10$RHttySZHDbKUw9e9FQlWIOxf6wFyF02NoPdPpJxKLWoj/D9HZjSrq', 'Chloe', 'Bennett', '1990-10-10', 'https://api.dicebear.com/7.x/avataaars/svg?seed=chloe_bennett&backgroundColor=f8c471', 'chloeb', 'Fashion designer and stylist. Sharing the latest trends and style tips 👗 #Fashion #Style', false, datetime('now', '-1 day'), datetime('now')),
('noah.kim@example.com', '$2a$10$RHttySZHDbKUw9e9FQlWIOxf6wFyF02NoPdPpJxKLWoj/D9HZjSrq', 'Noah', 'Kim', '1993-03-15', 'https://api.dicebear.com/7.x/avataaars/svg?seed=noah_kim&backgroundColor=aed6f1', 'noahkim', 'Gamer and eSports enthusiast. Streaming gameplay and sharing tips for competitive gaming 🎮 #Gaming #eSports', false, datetime('now', '-1 day'), datetime('now'));